config/routes.rb
Rails.application.routes.draw do
  root 'cocktails#index'

  delete 'doses/destroy'

    resources :cocktails, only: [:index, :show, :create, :new] do
      resources :doses, only: [:new, :create]
    end

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

end

app/models/dose.rb
class Dose < ActiveRecord::Base
belongs_to :cocktail
belongs_to :ingredient
validates :description, :cocktail, :ingredient, presence: true
validates_uniqueness_of :cocktail, scope: :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses
  has_many :cocktails, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
     @cocktail = Cocktail.find(cocktail_params)
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)

    redirect_to cocktails_path
  end

  def new
    @cocktail = Cocktail.new
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def destroy
    @dose = Dose.find(params[:id])

    @dose.destroy
  end

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.create(dose_params)
  end

  private
  def dose_params
    params.require(:dose).permit(:description, :cocktail, :ingredient)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<div class="container">
 <div class="row">
   <div class="col-sm-8 col-sm-offset-2">

     <% @cocktailss.each do |cocktail|%>
     <article>
       <%= link_to cocktail_path(cocktail) do %>
       <h3><%= cocktail.name %></h3>
       <% end %>
       <p><%= ingredient.name %></p>
       <p><%= dose.description %></p>
     </article>
     <% end %>

   </div>
 </div>
</div>

app/views/cocktails/new.html.erb
<h1>Cocktails#new</h1>
<p>Find me in app/views/cocktails/new.html.erb</p>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= link_to cocktail_path %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/show.html.erb
<h1>Cocktails#show</h1>
<p>Find me in app/views/cocktails/show.html.erb</p>

<div class="container">
 <div class="row">
   <div class="col-sm-8 col-sm-offset-2">

     <article>
       <h3><%= @cocktail.name %></h3>
       <p><%= @ingredient.name %></p>
       <p><%= @dose.description %></p>
     </article>

     <%= link_to 'Return to main page', cocktails_path %>

   </div>
 </div>
</div>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MisterCocktail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>